import type { editor } from "monaco-editor";

export const LESSONIQUE_DEEP_OCEAN_THEME_ID = "lessonique-deep-ocean";

export const LESSONIQUE_DEEP_OCEAN_BACKGROUND = "#061826";

export const lessoniqueDeepOceanTheme: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "6F8F9F", fontStyle: "italic" },
    { token: "keyword", foreground: "C792EA" },
    { token: "keyword.control", foreground: "C792EA" },
    { token: "string", foreground: "A8D89C" },
    { token: "number", foreground: "F78C6C" },
    { token: "type", foreground: "82AAFF" },
    { token: "type.identifier", foreground: "82AAFF" },
    { token: "identifier", foreground: "D6E9F2" },
    { token: "function", foreground: "82AAFF" },
    { token: "tag", foreground: "7FDBCA" },
    { token: "attribute.name", foreground: "FFCB6B" },
    { token: "delimiter", foreground: "89DDFF" },
    { token: "operator", foreground: "89DDFF" },
    { token: "regexp", foreground: "ECC48D" },
  ],
  colors: {
    "editor.background": LESSONIQUE_DEEP_OCEAN_BACKGROUND,
    "editor.foreground": "#D6E9F2",
    "editor.lineHighlightBackground": "#0B2233",
    "editor.lineHighlightBorder": "#00000000",
    "editor.selectionBackground": "#14536B99",
    "editor.inactiveSelectionBackground": "#0F3C4E88",
    "editor.selectionHighlightBackground": "#1D4E6370",
    "editor.wordHighlightBackground": "#1D4E6355",
    "editor.wordHighlightStrongBackground": "#2A607666",
    "editorCursor.foreground": "#54D6D8",
    "editorLineNumber.foreground": "#66889A",
    "editorLineNumber.activeForeground": "#C3E8F0",
    "editorGutter.background": LESSONIQUE_DEEP_OCEAN_BACKGROUND,
    "editorIndentGuide.background1": "#17384A",
    "editorIndentGuide.activeBackground1": "#2A6076",
    "editorWhitespace.foreground": "#20485C",
    "editorBracketMatch.background": "#123C4E",
    "editorBracketMatch.border": "#4FC3C7",
    "editor.findMatchBackground": "#5C4B1F",
    "editor.findMatchHighlightBackground": "#244D57",
    "editorWidget.background": "#091F2F",
    "editorWidget.border": "#1D4659",
    "editorHoverWidget.background": "#091F2F",
    "editorHoverWidget.border": "#1D4659",
    "editorSuggestWidget.background": "#091F2F",
    "editorSuggestWidget.border": "#1D4659",
    "editorSuggestWidget.selectedBackground": "#12394B",
    "editorSuggestWidget.highlightForeground": "#54D6D8",
    "input.background": "#0A2334",
    "input.border": "#1D4659",
    "focusBorder": "#3AAFB9",
    "scrollbarSlider.background": "#2A607666",
    "scrollbarSlider.hoverBackground": "#3A7C8F88",
    "scrollbarSlider.activeBackground": "#4B94A7AA",
    "editorOverviewRuler.border": "#0A2232",
  },
};
